### ISSUE TITLE
Specify score column in mzTab file

### ISSUE THREAD

**Issue by bittremieux** [mpc-bioinformatics/pia#149]
I have two score columns in mzTab files generated by [ANN-SoLo](https://github.com/bittremieux/ANN-SoLo):

- The shifted dot product score, accession `MTD	psm_search_engine_score[1]	[MS, MS:1001143, search engine specific score for PSMs,]`
- The (subgroup) FDR, accession `MTD	psm_search_engine_score[2]	[MS, MS:1002354, PSM-level q-value,]`

PIA doesn't seem to know how to handle a search engine specific score, which makes sense because it can be anything. However, I haven't been able to figure out how to tell PIA to ignore the `psm_search_engine_score[1]` column in the mzTab file and use the `psm_search_engine_score[2]` column instead. As a result, when I run PIA on these mzTab files I get the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Type must not be null or of type UNKNOWN_SCORE: [MS, MS:1001143, search engine specific score for PSMs, ]
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.getBasicScoreModelForParam(MzTabParser.java:752)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.parsePSMScore(MzTabParser.java:721)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.lambda$parsePSMScores$9(MzTabParser.java:696)
at java.base/java.util.TreeMap.forEach(TreeMap.java:1002)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.parsePSMScores(MzTabParser.java:695)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.parsePSM(MzTabParser.java:556)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.parsePSMs(MzTabParser.java:521)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.parseFile(MzTabParser.java:240)
at de.mpc.pia.intermediate.compiler.parser.MzTabParser.getDataFromMzTabFile(MzTabParser.java:186)
at de.mpc.pia.intermediate.compiler.parser.InputFileParserFactory$InputFileTypes$3.parseFile(InputFileParserFactory.java:119)
at de.mpc.pia.intermediate.compiler.parser.InputFileParserFactory.getDataFromFile(InputFileParserFactory.java:450)
at de.mpc.pia.intermediate.compiler.PIACompiler.getDataFromFile(PIACompiler.java:257)
at de.mpc.pia.intermediate.compiler.PIACompiler.parseCommandLineInfile(PIACompiler.java:1347)
at de.mpc.pia.intermediate.compiler.PIACompiler.parseCommandLineInfiles(PIACompiler.java:1302)
at de.mpc.pia.intermediate.compiler.PIACompiler.main(PIACompiler.java:1256)
```

I've used the following command to run PIA version 1.3.10:

`java -cp pia-1.3.10/pia-1.3.10.jar de.mpc.pia.intermediate.compiler.PIACompiler -infile b10000_ZNF230.mztab -name pia_test -outfile b10000_ZNF230.xml`

I've attached the mzTab file for reference (renamed to .txt to appease GitHub): [b10000_ZNF230.txt](https://github.com/mpc-bioinformatics/pia/files/3929285/b10000_ZNF230.txt)

How can I process this file using PIA? Thanks.

**Comment by julianu** [comment]
Hej Wout,

Actually, the fastest way to get it running with PIA would be to add the ANN-solo terms to the PSI-OBO by asking @germa . Afterrards, PIA should directly use the updated PSI-OBO and your files should be processed correctly.

Otherwise, I could add a way to add generic scores, but that might take some more time right now, I am afraid.

**Comment by bittremieux** [comment]
Thanks for the tips. I've written a simple post-processing script to remove the dot product score column from my mzTab files. There's still a q-value score column as well that PIA is able to use.

This issue can be closed or not depending on your preference.

**Comment by julianu** [comment]
Ok, I will mark this as solved and put a generic score parser on my TODO.
